openapi: 3.0.0
info:
  title: urlshortner
  version: 1.0.0
servers:
  - url: 'http://urlshortner.test'
paths:
  /api/shorten:
    post:
      tags:
        - Save Url Record API
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                long_url:
                  type: string
                  example: >-
                    https://stackoverflow.com/questions/37102841/laravel-change-pagination-data
                private:
                  type: boolean
                  example: true
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Url has been successfully shorten.'
                  data:
                    type: object
                    $ref: '#/components/schemas/Url'
  /api/url-list:
    get:
      tags:
        - Get Public Url Record List API
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  message: 
                    type: string
                  data: 
                    type: object
                    properties: 
                      current_page: 
                        type: integer
                        example: 1
                      data: 
                        type: array
                        items: 
                          $ref: '#/components/schemas/Url'
                      first_page_url: 
                        type: string
                      from: 
                        type: integer
                        example: 1
                      next_page_url: 
                        type: string
                        format: nullable
                      path: 
                        type: string
                      per_page: 
                        type: integer
                        example: 20
                      prev_page_url: 
                        type: string
                        format: nullable
                      to: 
                        type: integer
                        example: 4
components:
  schemas:
    StandardResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
        message:
          type: string
    Error:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          example: false
    Url:
      type: object
      properties:
        id: 
          type: integer
          example: 221
        long_url: 
          type: string
        short_url: 
          type: string
        private: 
          type: integer
          example: 1
        created_at: 
          type: string
        updated_at: 
          type: string
        clicks_count: 
          type: integer
          example: 5